import { AngleId } from '@types';

const BASE64_IMG =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAABc0lEQVR4nO3SQQ0CMQwDQd7/pTdxSs0k4dndW52CARzwG8rBF0v9fT8/tXgCxhhiinmmGKKOeY4wzQfepfY+vWXp8AAAAAAAD4M8zPgdcGAPCnW19p54BkNenEAAAAAAAAAIArzfMhIBAAAAAA8Fj/6v9h3QgAAAAAAIBd8v4PAAAAAADgQPzL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAHhq/Ev4AQAAAAAAeGr8S/gBAAAAAAB4avxL+AEAAAAAAOAX9gGtrgdgj56Q+AAAAABJRU5ErkJggg==';

export const ANGLE_PLACEHOLDERS: Record<AngleId, string> = {
  front: BASE64_IMG,
  right45: BASE64_IMG,
  left45: BASE64_IMG,
  top: BASE64_IMG,
  donor: BASE64_IMG
};
